//local host

### Get all contacts
GET http://localhost:8080/contacts/

### Get a single contact
GET http://localhost:8080/contacts/6787267906da489a980e7254

### Create contact
POST http://localhost:8080/contacts/ http/1.1
Content-Type: application/json

{
    "firstName": "Sonya",
    "lastName": "Beauchaine",
    "email": " sonaybeauchaine@example.com",
    "favoriteColor": "Pink",
    "birthday": "2011-01-01"
}

### Put contact
PUT http://localhost:8080/contacts/6787267906da489a980e7254 http/1.1    
Content-Type: application/json

{
    "firstName": "Mandi",
    "lastName": "Beauchaine",
    "email": " mandibeauchaine@example.com",
    "favoriteColor": "Yellow",
    "birthday": "1981-01-13"
}

### Delete contact
DELETE http://localhost:8080/contacts/6792e69af833211ed4a9a620 http/1.1



//Render server
### Get all contacts
GET https://cse341-mandi-beauchaine.onrender.com/contacts/

### Get a single contact
GET https://cse341-mandi-beauchaine.onrender.com/contacts/6787267906da489a980e7254

### Create contact
POST https://cse341-mandi-beauchaine.onrender.com/contacts/ http/1.1
Content-Type: application/json

{
    "firstName": "Sonya",
    "lastName": "Beauchaine",
    "email": " sonaybeauchaine@example.com",
    "favoriteColor": "Pink",
    "birthday": "2011-01-01"
}

### Put contact
PUT https://cse341-mandi-beauchaine.onrender.com/contacts/6787267906da489a980e7254 http/1.1    
Content-Type: application/json

{
    "firstName": "Mandi",
    "lastName": "Beauchaine",
    "email": " mandibeauchaine@example.com",
    "favoriteColor": "Yellow",
    "birthday": "1981-01-13"
}

### Delete contact
DELETE https://cse341-mandi-beauchaine.onrender.com/contacts/6787267906da489a980e7254 http/1.1